### PR TITLE
Update language versions

### PR DESCRIPTION
**Pull request by igoose1**
Language versions are up to date on 7 May 2021. Look at diff to see
more.

Note: I haven't changed LanguageExtn.

### CODE REVIEW

**Comment by infalmo** [comment]
Thanks for the PR!
Can you please share the code you used to extract latest compilers and their id's for future reference?

**Comment by igoose1** [comment]
> Thanks for the PR!
> Can you please share the code you used to extract latest compilers and
> their id's for future reference?

To be honest, whole processing was done in an interactive Python shell. I
copied part of HTML from the browser, found matched by a regexp strings and
format them in Go.

I've just edited (threw away regexp) and assembled a code in the Python 3
script file. It's not Go, yep, but I hope it will be useful in a future.


------------------------ >8 ------------------------

"""
The following script extracts ids of languages from codeforces submit page.

It uses stdin to read html of the page.

Expected procedure:

	1) Log in codeforces in the browser, open
	https://codeforces.com/problemset/submit and save it in /tmp/submit.html.

	2) python -m pip install bs4

	3) python languages.py < /tmp/submit.html

	4) Paste output in cpt-lib/codeforces/languages.go.

	5) Re-format code with go fmt.
"""

# Copyright (C) 2021 Oskar Sharipov <oskarsh[at]riseup[dot]net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Dict, List
import sys

from bs4 import BeautifulSoup


def extract_langs(raw_html: str):
    html = BeautifulSoup(raw_html, features="lxml")
    select = html.body.find("select", attrs={"name": "programTypeId"})
    options = select.find_all("option")

    result: Dict[str, str] = {}
    for option in options:
        key, value = option.get_text(), option.get("value")
        result[key] = value
    return result


def main():
    if "--help" in sys.argv:
        print(__doc__.strip(), file=sys.stderr)
        return

    raw_html = sys.stdin.read()
    try:
        langs = extract_langs(raw_html)
    except AttributeError:
        print("error: cannot parse html.", file=sys.stderr)
        return 1

    result: List[str] = []
    result.append("{")
    for key, value in sorted(langs.items(), key=lambda x: x[0]):
        result.append(f'\t"{key}": "{value}",')
    result.append("}")
    result.append("// TODO: do go fmt.")
    print("\n".join(result))


if __name__ == "__main__":
    exit_code = main()
    if exit_code:
        sys.exit(exit_code)

------------------------ >8 ------------------------

-- 
Oskar Sharipov
gpg fingerprint: BAC3 F049 748A D098 A144  BA89 0DC4 EA75 714C 75B5

**Comment by igoose1** [comment]
Well, Github shows a code in the mail awfully. I uploaded a script in gist: https://gist.githubusercontent.com/igoose1/921954377c4677776b5ee479f48624ea/raw/8934e450818af34b3cb77efdbfd22e4eb05231dc/languages.py.

**Comment by infalmo** [comment]
Thanks a lot for this!

**Review by infalmo — APPROVED** [review]

**Pull request merged**
